global:
  resolve_timeout: 1m

receivers:
- name: System-Team
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 6612849064:AAGR795EyHyn278L0WRLeqiTyBuCWRRhjMg
    chat_id: -998222571
    #template: template.tmpl  # Thay 'template-name' bằng tên template bạn đã tạo
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""

- name: BV-BachMai-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-932865047'
    send_resolved: true
  # telegram_configs:
  # - api_url: https://api.telegram.org
  #   bot_token: 5765051913:AAEXYcQKE0h8FTiC8Ba0DgNutliSMBbXAjw
  #   chat_id: -932865047
  #   #template: template.tmpl 
  #   disable_notifications: false
  #   http_config:
  #     follow_redirects: true
  #   send_resolved: true
  #   parse_mode: ""

- name: Mediplus-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'
    send_resolved: true
  # telegram_configs:
  # - api_url: https://api.telegram.org
  #   bot_token: 5765051913:AAEXYcQKE0h8FTiC8Ba0DgNutliSMBbXAjw
  #   chat_id: -866646704
  #   #template: template.tmpl
  #   disable_notifications: false
  #   http_config:
  #     follow_redirects: true
  #   send_resolved: true
  #   parse_mode: ""

- name: Jenkins-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'
    send_resolved: true

route:
  continue: false
  group_by: ['job','severity']
  group_interval: 1m
  group_wait: 30s
  repeat_interval: 1m
  receiver: System-Team
  routes:
  - match_re: 
      app_type: (bachmai|mediplus)
    receiver: System-Team 
    routes:
    # Bạch Mai group
    - match:
        app_type: bachmai
        instance : "10.0.0.210:9100"
      receiver: BV-BachMai-telegram
    # Mediplus group
    - match:
        app_type: mediplus
        instance: ".+"
        params:
          instance: [".+"]
      receiver: Mediplus-telegram
    # - match:
    #     app_type: jenkins
    #   receiver: Jenkins-telegram

templates:
- /etc/alertmanager/*.tmpl
# route:
#   receiver: 'slack'

# receivers:
#   - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'