global:
  resolve_timeout: 1m

receivers:
- name: System-Team
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 6612849064:AAGR795EyHyn278L0WRLeqiTyBuCWRRhjMg
    chat_id: -998222571
    #template: template.tmpl  # Thay 'template-name' bằng tên template bạn đã tạo
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""

- name: BV-BachMai-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-932865047'
    send_resolved: true

- name: Mediplus-telegram
  webhook_configs:
  - url: 'http://10.0.0.232:9087/alert/-866646704'
    send_resolved: true

- name: System-Container
  # webhook_configs:
  # - url: 'http://10.0.0.13:9088/alert/-999710731'
  #   send_resolved: true
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 5765051913:AAEXYcQKE0h8FTiC8Ba0DgNutliSMBbXAjw
    chat_id: -999710731
    #template: template.tmpl
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""

route:
  continue: false
  group_by: ['job','severity','instance']
  group_interval: 1m
  group_wait: 30s
  repeat_interval: 1m
  receiver: System-Team
  
  routes:
  - match_re: 
      app_type: (bachmai|mediplus)
    receiver: System-Team 
    routes:
# Bạch Mai group
    - match:
        app_type: bachmai
        instance : 10.0.0.210:9100
      receiver: BV-BachMai-telegram
# Mediplus group
    - match:
        app_type: mediplus
        instance: 10.0.0.211:19100
      receiver: Mediplus-telegram
      group_wait: 1s
    - match:
        app_type: mediplus
        instance: 10.0.0.55:9100
      receiver: Mediplus-telegram
      group_wait: 3s

#DrALLEN Containers
  - match_re: 
      app_type: (dr-allen-cpu-redis|dr-allen-cpu-kafka|dr-allen-cpu-kafka-ui)
      group: Container CPU For Dr Allen Server
    receiver: System-Container
    routes:
    - match:
        alertname: Redis Container Cpu High
        app_type: dr-allen-cpu-redis
        group : Container CPU For Dr Allen Server
        category: cpu
      receiver: System-Container
      group_wait: 1s

    - match:
        alertname: Kafka Container Cpu High
        app_type: dr-allen-cpu-kafka
        group : Container CPU For Dr Allen Server
        category: cpu
        receiver: System-Container
        group_wait: 2s

    - match:
        alertname: Kafka UI Container Cpu High
        app_type: dr-allen-cpu-kafka-ui
        group : Container CPU For Dr Allen Server
        category: cpu
      receiver: System-Container
      group_wait: 3s
        
    # - match:
    #     alertname: Container Memory For Dr Allen Server
    #     app_type: dr-allen-memory
    #     instance: 10.0.0.55:11092
    #     category: memory
    #   receiver: System-Container
# rule_files:
# - 'containers/DrAllen/CPU/DrAllenCpu.yml'
# - 'containers/DrAllen/RAM/DrAllenRam.yml'

templates:
- /etc/alertmanager/*.tmpl

# route:
#   receiver: 'slack'

# receivers:
#   - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'