global:
  resolve_timeout: 1m

receivers:
- name: System-Team
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 6612849064:AAGR795EyHyn278L0WRLeqiTyBuCWRRhjMg
    chat_id: -998222571
    #template: template.tmpl
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""

- name: BV-BachMai-telegram
  webhook_configs:
  - url: 'http://10.0.0.13:9088/alert/-945958075'
    send_resolved: true
  # telegram_configs:
  # - api_url: https://api.telegram.org
  #   bot_token: 5765051913:AAEXYcQKE0h8FTiC8Ba0DgNutliSMBbXAjw
  #   chat_id: -932865047
  #   #template: template.tmpl 
  #   disable_notifications: false
  #   http_config:
  #     follow_redirects: true
  #   send_resolved: true
  #   parse_mode: ""

- name: Mediplus-telegram
  # webhook_configs:
  # - url: 'http://10.0.0.13:9088/alert/-945958075'
  #   send_resolved: true
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 6588801252:AAFJD4d1WW0L36mS_HfRlzTBIy3B7KJkIvc
    chat_id: -824908019
    #template: template.tmpl
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""

- name: System-Container
  webhook_configs:
  - url: 'http://10.0.0.13:9088/alert/-824908019'
    send_resolved: true

- name: Systems
#  webhook_configs:
#  - url: 'http://10.0.0.13:9087/alert/-824908019'
#    send_resolved: true
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 6588801252:AAFJD4d1WW0L36mS_HfRlzTBIy3B7KJkIvc
    chat_id: -824908019
    #template: template.tmpl
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""


route:
  continue: false
  group_by: ['job','severity','instance']
  group_interval: 1m
  group_wait: 30s
  repeat_interval: 1m
  receiver: System-Team
    
  routes:
  - match:
      app_type: Port
    receiver: System-Team 

  - match_re: 
      app_type: (bachmai|mediplus)
    receiver: System-Team 
    routes:
# Bạch Mai group
    - match:
        app_type: bachmai
        instance : 10.0.0.210:9100
      receiver: BV-BachMai-telegram
# Mediplus group
    - match:
        app_type: mediplus
        instance: 10.0.0.211:19100
      receiver: Mediplus-telegram
      group_wait: 1s
    - match:
        app_type: mediplus
        instance: 10.0.0.55:9100
      receiver: Mediplus-telegram
      group_wait: 3s

#DrALLEN Containers
  - match_re: 
      app_type: (dr-allen-cpu|dr-allen-memory|test service dead)
    receiver: System-Container
    routes:

    - match:
        alertname: Zookeeper Container Cpu High
        app_type: dr-allen-cpu
        instance: 10.0.0.55:11092
        category: cpu
      receiver: System-Container

    - match:
        alertname: Frontend Quanlybackup Container Cpu High
        app_type: dr-allen-cpu
        instance: 10.0.0.55:11092
        category: cpu
      receiver: System-Container

    - match:
        alertname: Golang App Container Cpu High
        app_type: dr-allen-cpu
        instance: 10.0.0.55:11092
        category: cpu
      receiver: System-Container

    - match:
        alertname: searching-service Container Cpu High
        app_type: dr-allen-cpu
        instance: 10.0.0.55:11092
        category: cpu
      receiver: System-Container

    - match:
        alertname: disk-partition-service Container Cpu High
        app_type: dr-allen-cpu
        instance: 10.0.0.55:11092
        category: cpu
      receiver: System-Container

    - match:
        alertname: Redis Container Cpu High
        app_type: dr-allen-cpu
        instance: 10.0.0.55:11092
        category: cpu
      receiver: System-Container

    - match:
        alertname: Redis Container Tắt
        app_type: dr allen service dead
        instance: 10.0.0.55:11092
        category: service
      receiver: Systems

    - match:
        alertname: Frontend Quản lý máy chủ Container Tắt
        app_type: dr allen service dead
        instance: 10.0.0.55:11092
        category: service
      receiver: Systems

    - match:
        alertname: Kafka Container Die
        app_type: dr allen service dead
        instance: 10.0.0.55:11092
        category: service
      receiver: System-Container

  - match:
      alertname: Container Tắt
      app_type: test service dead
      instance: 10.0.0.55:11092
      category: service
    receiver: Systems

  - match:
      alertname: HUY Container ĐÃ TẮT
      app_type: test service dead
      instance: 10.0.0.55:8080
      category: service
    receiver: Systems

  - match:
      alertname: Container Exited !!! HUY Alert
      app_type: service die
      instance: 10.0.0.55:8080
      category: service
    receiver: Systems

templates:
- /etc/alertmanager/*.tmpl

# route:
#   receiver: 'slack'

# receivers:
#   - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'