groups:
  - name: Service Die or Container Shutdown For Dr Allen Server
    rules:

    - alert: Redis Container Tắt
      # expr: container_memory_usage_bytes{name="redis-server"} < 1.5e+10
      expr: absent(container_last_seen{name="redis-server",instance="10.0.0.55:11092"}) == 1
      for: 1m
      labels:
        severity: KHẨN
        app_type: dr-allen-service-dead
        category: service
      annotations:
        summary: "REDIS container đã TẮT tại : [ {{ $labels.instance }} ]  trong 1 phút vừa qua"
        description: |
          REDIS CONTAINER HIỆN TẠI ĐANG TẮT........

    - alert: Frontend Quản lý máy chủ Container Tắt
      expr: absent(container_last_seen{name="frontend_quanlybackup_dev",instance="10.0.0.55:11092"}) == 1
      for: 1m
      labels:
        severity: KHẨN
        app_type: dr-allen-service-dead
        category: service
      annotations:
        summary: "FRONTEND QUẢN LÝ MÁY CHỦ container đã TẮT tại : [ {{ $labels.instance }} ]  trong 1 phút vừa qua"
        description: |
          FRONTEND QUẢN LÝ MÁY CHỦ CONTAINER HIỆN TẠI ĐANG TẮT........

    - alert: Kafka Container Die
      expr: absent(container_last_seen{name="kafka-isofh",instance="10.0.0.55:11092"}) == 1
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-service-dead
        category: service
      annotations:
        summary: "KAFKA container is SHUTDOWN on {{ $labels.instance }} for more than 1 minutes"
        description: |
          HUY NG
          KAFKA CONTAINER IS DEAD

    - alert: Kafka UI Container Die
      expr: absent(container_last_seen{name="kafka-ui-isofh",instance="10.0.0.55:11092"}) == 1
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-service-dead
        category: service
      annotations:
        summary: "KAFKA UI container is SHUTDOWN on {{ $labels.instance }} for more than 1 minutes"
        description: |
          HUY NG
          KAFKA UI CONTAINER IS DEAD