groups:
- name: Container


  rules:
  - alert: Container Status 
    expr: container_state_status{status="exited",name=~"golang-app"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: golang-app
      app_type: Server Test
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Status 
    expr: container_state_status{status="exited",name=~"searching-service"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: searching-service
      app_type: Server Test
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Status 
    expr: container_state_status{status="exited",name=~"flamboyant_dubinsky"} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: flamboyant_dubinsky
      app_type: Server Test
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 



################################################  
################## RAM #########################  
################################################  

  - alert: Container Memory
    expr: sum(container_memory_working_set_bytes{job='isofhlocal', name='flamboyant_dubinsky'}) / sum(container_spec_memory_limit_bytes{job="isofhlocal", id="/", instance='10.0.0.55:19093'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-memory    
      container_name: flamboyant_dubinsky
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **flamboyant_dubinsky**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%


  - alert: Container Memory
    expr: sum(container_memory_working_set_bytes{job='isofhlocal', name='golang-app'}) / sum(container_spec_memory_limit_bytes{job="isofhlocal", id="/", instance='10.0.0.55:19093'}) * 100 > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-memory    
      container_name: golang-app
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **golang-app**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%


  - alert: Container Memory
    expr: sum(container_memory_working_set_bytes{job='isofhlocal', name='searching-service'}) / sum(container_spec_memory_limit_bytes{job="isofhlocal", id="/", instance='10.0.0.55:19093'}) > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-memory    
      container_name: searching-service
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **searching-service**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%


################################################  
################## CPU #########################  
################################################  

  - alert: Container CPU searching-service
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='isofhlocal',name='searching-service'}[1m])) BY (instance, name) * 100) > 90
    for: 10s
    labels:
      severity: khẩn cấp
      app_type: Server Test
      category: container-memory    
      container_name: searching-service
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%
