# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'Hospitals'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules/BachMaiRules.yml'
  - 'rules/CheckDomainStatus.yml'
  - 'rules/CheckPortContainer.yml'
  - 'containers/DrAllen/DEAD/DrAllenServiceDead.yml'
  - "rules/NhiDongThanhPho.yml"
  - "rules/phongkham40.yml"
  - "rules/benhviene.yml"
  - "rules/benhvienquany110.yml"
  - "rules/benhvienthanhhoa.yml"
  - "rules/daihocy.yml"
  - "rules/drallen.yml"
  - "rules/benhviensaintpaul.yml"
  - "rules/phongkhammediplus.yml"
  - "rules/trungtamtimmach.yml"
  - "rules/benhvienphoi.yml"
  - "rules/benhvienbachmai.yml"
  - "rules/phongkhamykhn.yml"
  - "rules/ivirse.yml"
  - "rules/isofhcare.yml"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'Bach-Mai'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.210:9100']

  - job_name: 'Mediplus'
    scrape_interval: 5s
    static_configs:
      - targets: ["10.0.0.55:9100","10.0.0.211:19100"]

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
    basic_auth:
      username: admin
      password: daniel@0908

  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080
    static_configs:
      - targets: ['10.0.0.55:19093']

  - job_name: 'docker-state'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.55:19092']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100


#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']

  - job_name: 'Check Domain Status'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets:
        - http://10.0.0.211:19400 # Target to probe with http on port 8080.
        - http://10.0.0.235:19400
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
  
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['10.0.0.235:19400']

  - job_name: blackbox_all
    metrics_path: /probe
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    dns_sd_configs:
      - names:
          - example.com
          - prometheus.io
        type: A
        port: 443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/  # Make probe URL be like https://1.2.3.4:443/
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
      - source_labels: [__meta_dns_name]
        target_label: __param_hostname  # Make domain name become 'Host' header for probe requests
      - source_labels: [__meta_dns_name]
        target_label: vhost  # and store it in 'vh

  - job_name: 'Check_Port_Container'
    params:
      module:
      - tcp_connect
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /probe
    scheme: http
    static_configs:
    - targets:
      - 10.0.0.235:5000
      - 10.0.0.235:9087
    relabel_configs:
    - source_labels: [__address__]
      separator: ;
      regex: (.*)
      target_label: __param_target
      replacement: $1
      action: replace
    - source_labels: [__param_target]
      separator: ;
      regex: (.*)
      target_label: instance
      replacement: $1
      action: replace
    - separator: ;
      regex: (.*)
      target_label: __address__
      replacement: 10.0.0.101:9115
      action: replace