groups:
  - name: Container's Port
    rules:

    - alert: Port Container Down
      expr: probe_success{job="Check_Port_Container"} == 0
      app_type: Port
      labels:
        severity: critical
      annotations:
        description: |-
          Node memory is filling up (< 10% left)
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
        summary: Host out of memory (instance {{ $labels.instance }})