groups:
  - name: Container CPU For Dr Allen Server
    rules:

    - alert: Kafka Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="kafka-isofh"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
        container_name: kafka-isofh
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: Kafka UI Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="kafka-ui-isofh"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
        container_name: kafka-ui-isofh
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: Zookeeper Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="zookeeper-isofh"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: Frontend Quanlybackup Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="kafka-ui-isofh"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: Golang App Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="golang-app"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: searching-service Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="searching-service"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: disk-partition-service Container Cpu High
      # expr: rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="redis-server"}[1m])
      expr: 100 * (1 - rate(container_cpu_usage_seconds_total{instance="10.0.0.55:11092",name="flamboyant_dubinsky"}[5m])) > 80
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
      annotations:
        summary: "CPU of Redis container is high on {{$labels.instance}}"
        description: |
          HUY NG
          CPU of Redis container is high for more than 1 minutes

    - alert: Redis Container Cpu High
      expr: rate(container_cpu_usage_seconds_total{name="redis-server"}[1m]) 
      for: 1m
      labels:
        severity: critical
        app_type: dr-allen-cpu
        category: cpu
        container_name: redis-server
      annotations:
        summary: "CPU of grafana container is high on {{ $labels.instance }}"
        description: |
          HUY NG
          CPU of grafana container is high for more than 1 minutes
