groups:
- name: Container
  rules:
# 1 ------------------------------------------------------------ monitor -----------------------------------------------------------------------
  - alert: Container Status monitor
    expr: container_state_status{status="exited",name=~"monitor",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: monitor
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory monitor
    expr: (container_memory_working_set_bytes{job='dhy', name='monitor'}) / (container_spec_memory_limit_bytes{job="dhy", name='monitor', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: monitor
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **monitor**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU monitor
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='monitor',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: monitor
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 2 ------------------------------------------------------------ emr-config -----------------------------------------------------------------------

  - alert: Container Status emr-config
    expr: container_state_status{status="exited",name=~"emr-config",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: emr-config
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory emr-config
    expr: (container_memory_working_set_bytes{job='dhy', name='emr-config'}) / (container_spec_memory_limit_bytes{job="dhy", name='emr-config', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: emr-config
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **emr-config**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU emr-config
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='emr-config',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: emr-config
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 3 ------------------------------------------------------------ emr-zuul-bvp-production -----------------------------------------------------------------------

  - alert: Container Status emr-zuul-bvp-production
    expr: container_state_status{status="exited",name=~"emr-zuul-bvp-production",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: emr-zuul-bvp-production
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory emr-zuul-bvp-production
    expr: (container_memory_working_set_bytes{job='dhy', name='emr-zuul-bvp-production'}) / (container_spec_memory_limit_bytes{job="dhy", name='emr-zuul-bvp-production', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: emr-zuul-bvp-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **emr-zuul-bvp-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU emr-zuul-bvp-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='emr-zuul-bvp-production',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: emr-zuul-bvp-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 4 ------------------------------------------------------------ emr-eureka-bvp-production -----------------------------------------------------------------------

  - alert: Container Status emr-eureka-bvp-production
    expr: container_state_status{status="exited",name=~"emr-eureka-bvp-production",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: emr-eureka-bvp-production
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory emr-eureka-bvp-production
    expr: (container_memory_working_set_bytes{job='dhy', name='emr-eureka-bvp-production'}) / (container_spec_memory_limit_bytes{job="dhy", name='emr-eureka-bvp-production', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: emr-eureka-bvp-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **emr-eureka-bvp-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU emr-eureka-bvp-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='emr-eureka-bvp-production',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: emr-eureka-bvp-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 5 ------------------------------------------------------------ report-service-bvp-production -----------------------------------------------------------------------

  - alert: Container Status report-service-bvp-production
    expr: container_state_status{status="exited",name=~"report-service-bvp-production",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: report-service-bvp-production
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory report-service-bvp-production
    expr: (container_memory_working_set_bytes{job='dhy', name='report-service-bvp-production'}) / (container_spec_memory_limit_bytes{job="dhy", name='report-service-bvp-production', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: report-service-bvp-production
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **report-service-bvp-production**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU report-service-bvp-production
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='report-service-bvp-production',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: report-service-bvp-production
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 6 ------------------------------------------------------------ redis-cache -----------------------------------------------------------------------

  - alert: Container Status redis-cache
    expr: container_state_status{status="exited",name=~"redis-cache",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: redis-cache
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory redis-cache
    expr: (container_memory_working_set_bytes{job='dhy', name='redis-cache'}) / (container_spec_memory_limit_bytes{job="dhy", name='redis-cache', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: redis-cache
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **redis-cache**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU redis-cache
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='redis-cache',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: redis-cache
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 7 ------------------------------------------------------------ zipkin -----------------------------------------------------------------------

  - alert: Container Status zipkin
    expr: container_state_status{status="exited",name=~"zipkin",instance='10.0.30.150:8098'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: zipkin
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory zipkin
    expr: (container_memory_working_set_bytes{job='dhy', name='zipkin'}) / (container_spec_memory_limit_bytes{job="dhy", name='zipkin', instance='10.0.30.150:8098'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: zipkin
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **zipkin**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU zipkin
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='zipkin',instance='10.0.30.150:8098' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: zipkin
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

  