groups:
- name: Container
  rules:

# 1 ========================================================== bvp-production-device-management-frontend ==========================================================
  - alert: Container Status bvp-production-device-management-frontend
    expr: container_state_status{status="exited",name=~"bvp-production-device-management-frontend",instance='10.0.30.224:9092'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: bvp-production-device-management-frontend
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory bvp-production-device-management-frontend
    expr: (container_memory_working_set_bytes{job='dhy', name='bvp-production-device-management-frontend'}) / (container_spec_memory_limit_bytes{job="dhy", name='bvp-production-device-management-frontend', instance='10.0.30.224:9092'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: bvp-production-device-management-frontend
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **bvp-production-device-management-frontend**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU bvp-production-device-management-frontend
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='bvp-production-device-management-frontend',instance='10.0.30.224:9092' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: bvp-production-device-management-frontend
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

# 2 ========================================================== bvp-production-service-device ==========================================================

  - alert: Container Status bvp-production-service-device
    expr: container_state_status{status="exited",name=~"bvp-production-service-device",instance='10.0.30.224:9092'} == 1
    for: 1s
    labels:
      severity: khẩn cấp
      category: container-status
      container_name: bvp-production-service-device
      app_type: Bệnh Viện Phổi
    annotations:
      summary: Container exited
      description: |

       CONTAINER NAME:-  {{ $labels.name }}

       CONTAINER BỊ TẮT 

  - alert: Container Memory bvp-production-service-device
    expr: (container_memory_working_set_bytes{job='dhy', name='bvp-production-service-device'}) / (container_spec_memory_limit_bytes{job="dhy", name='bvp-production-service-device', instance='10.0.30.224:9092'}) * 100 > 90
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-memory    
      container_name: bvp-production-service-device
    annotations:
      summary: "RAM container quá 90%"
      description: |
      
        CONTAINER NAME: 
        
        **bvp-production-service-device**

        Thông tin cụ thể: 

          RAM USED: {{ printf "%.2f" $value}}% / 100%

  - alert: Container CPU bvp-production-service-device
    expr: (sum(rate(container_cpu_usage_seconds_total{name!="",job='dhy',name='bvp-production-service-device',instance='10.0.30.224:9092' }[1m])) BY (instance, name) * 100) > 500
    for: 30s
    labels:
      severity: khẩn cấp
      app_type: Bệnh Viện Phổi
      category: container-cpu    
      container_name: bvp-production-service-device
    annotations:
      summary: "CPU container quá 95%"
      description: |
      
        CONTAINER NAME: {{ $labels.name }}

        Thông tin cụ thể: 

          CPU USED : {{ printf "%.2f" $value}}%

  